todoapp/urls.py
from django.urls import path
from.import views
app_name='todoapp'
urlpatterns = [

    path('',views.add,name='add'),
    # path('details/',views.details,name='details'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.TaskUpadteview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.TaskDeleteview.as_view(),name='cbvdelete'),

]

todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from todoproject import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                            document_root=settings.STATIC_ROOT)
    urlpatterns  += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT )

todoapp/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.name

todoapp/forms.py
from.models import Task
from django import forms
# from django.forms import ModelForm

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields= '__all__'

todoapp/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from .models import Task
from.forms import TodoForm
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView

class Tasklistview(ListView):
    model= Task
    template_name= 'home.html'
    context_object_name= 'task'

class TaskDetailview(DetailView):
    model=Task
    template_name='detail.html'
    context_object_name= 'task'

class TaskUpadteview(UpdateView):
    model=Task
    template_name='update.html'
    context_object_name= 'task'
    fields=('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail',kwargs={'pk':self.object.id})

class TaskDeleteview(DeleteView):
    model=Task
    template_name='delete.html'
    success_url= reverse_lazy('todoapp:cbvhome')








# Create your views here.






def add(request):
    task1 = Task.objects.all()
    if request.method=="POST":
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=Task(name=name,priority=priority,date=date)
        task.save()

    return render(request,'home.html',{'task':task1})
#
# def details(request):
#
#     return render(request,'detail.html')


def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method =='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None,request.FILES,instance=task)
    if f. is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'task':task})

templates/base.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>

templates/delete.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Are you want to delete this?</p>
    <input type="submit">
<!--    <button type="submit">confirm</button>-->
</form>


{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="shadow card">
                    <div class="card-body">
                        <h5 class="card-title">{{task.name}}</h5>
                        <p><b>{{task.priority}}</b></p>
                        <p1>{{task.date}}</p1>
                        <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}"> Done</a>
                        <a class="btn btn-success" href="{% url 'todoapp:update'  task.id %}">Update</a>
                    </div>
                </div>

{% endblock %}

<!--{% for i in task %}-->
<!--{{i.name}}-->
<!--{{i.priority}}-->
<!--{{i.date}}-->
<!--{% endfor %}-->dblock %}

templates/edit.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{f.as_p}}
<!--    <input type="submit">-->
    <button type="submit">confirm</button>
</form>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
       <form method="POST" class="p-3 shadow">
           {% csrf_token %}
           <div class="form-group">
         <input type="text" class="form-control" name="task"placeholder="enter your task">
               </div>
               <div class="form-group">
          <input type="text"  class="form-control" name="priority" placeholder="enter your priority">
                   </div>
            <div class="form-group">
          <input type="date"  class="form-control" name="date" placeholder="enter your date">
                   </div>
           <input type="submit" class="btn btn-success">

    </form>


        </div>
            <div class="col-md-6">
                 <h4>Task to be completed</h4>
                   {% for i in task %}
                <div class="shadow card">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p><b>{{i.priority}}</b></p>
                        <p1>{{i.date}}</p1>
                        <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}"> Done</a>
                        <a class="btn btn-success" href="{% url 'todoapp:update'  i.id %}">Update</a>
                    </div>
                </div>
                      <br>
                     {% endfor %}
            </div>
        </div>
</div>

{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block content %}
<div class ="card">
    <div class="card-header">
        <div class="card-title">
            Task  Update
        </div>
    <div class="card-body">
       <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
<!--    <input type="submit">-->
    <button type="submit">confirm</button>
</form>

        </div>
    </div>
</div>


{% endblock %}